import esbuild from "esbuild";
import process from "process";
import fs from "fs-extra"; // To handle cleaning the output directory
import builtins from "builtin-modules";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outputDir = "dist"; // Output directory

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		'@codemirror/autocomplete',
		'@codemirror/closebrackets',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/comment',
		'@codemirror/fold',
		'@codemirror/gutter',
		'@codemirror/highlight',
		'@codemirror/history',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/matchbrackets',
		'@codemirror/panel',
		'@codemirror/rangeset',
		'@codemirror/rectangular-selection',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/stream-parser',
		'@codemirror/text',
		'@codemirror/tooltip',
		'@codemirror/view',
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outputDir}/main.js`,
	minify: prod,
});

const copyStaticFiles = () => {
	fs.copySync("manifest.json", `${outputDir}/manifest.json`);
	fs.copySync("styles.css", `${outputDir}/styles.css`);
	console.log("Copied static files to dist folder.");
};

if (prod) {
	await context.rebuild();
	copyStaticFiles(); // Copy static files for production build
	process.exit(0);
} else {
	await context.watch();
	copyStaticFiles(); // Copy static files during development
}
