name: Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Specify the Node.js version compatible with your project
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run the build command
      - name: Build the package
        run: npm run build